### ISSUE TITLE
Add Circular Slider Tool

### ISSUE THREAD

**Issue by dvbit** [AmoebeLabs/swiss-army-knife-card#133]
Implement round (arc) slider

To allow regulations for knob shaped  widgets

**Comment by AmoebeLabs** [comment]
The next release will have a experimantal (alpha state) Circular Slider.

Documentation will follow...

![image](https://user-images.githubusercontent.com/7996307/180645296-18fa313c-43e1-44d9-94b0-440025117c9f.png)

**Comment by dvbit** [comment]
Awesome!!!
