### ISSUE TITLE
Uncaught TypeError: this.entities[o] is undefined

### ISSUE THREAD

**Issue by ekutner** [AmoebeLabs/swiss-army-knife-card#163]
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [x] Yes, I'm sure that it is not a configuration mistake

## Bug description
Just installed SAK with HACS and the additional manual steps. I'm using storage mode for lovelace , so had to skip some steps but I believe it is still a valid installation.
Now I'm trying to get the first example view to work. I added the dashboards to the config and installed the two required integrations, however the view is not loading. In the browser console I get this error which probably explains why it doesn't work:
```
Uncaught TypeError: this.entities[o] is undefined
    set hass swiss-army-knife-card.js:697
	...
```

### To Reproduce
Just download the repo from github and add the dashboards.

### Desktop browser (please complete the following information):
 - OS: Windows
 - Browser: Firefox (but also tested with Chrome)
 - Version: 103.0.2

**Comment by AmoebeLabs** [comment]
This is an old issue, and probably an entity is not defined.

The latest versions give more feedback in the error messages.

Closing this issue
