### ISSUE TITLE
After complete installation error: Custom element does not exist: decluttering-card

### ISSUE THREAD

**Issue by WLammert** [AmoebeLabs/swiss-army-knife-card#167]
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [X] Yes, I'm sure that it is not a configuration mistake

## Bug description
I followed the complete installation guide. 
I also added the resource.yaml file from GUI.
I see the dashboards for examples and tutorials in the navigation menu. But if I navigate to examples SAKE1 and SAKE1-M3 are completely empty, and SAKE2 looks like this:
![image](https://user-images.githubusercontent.com/1142532/191783735-2454816d-e41f-4ff5-b5ef-23af5be22046.png)

### To Reproduce
just install as described in the introduction.

### Expected behavior
Probably the red elements shouldn't be there

### Desktop browser (please complete the following information):
 - OS: MAC
 - Browser CHROME
 - Version current

**Comment by fifou5555** [comment]
hello,

install "decluttering card" using HACS.
it's STEP 1B in the installation guide

**Comment by WLammert** [comment]
I did (screenshot attached)! As I told, I followed the complete guide, but still the issue...
<img width="392" alt="image" src="https://user-images.githubusercontent.com/1142532/192131603-9f6cafa4-896f-4c73-aecd-db1b6984bed0.png">

**Comment by ViRouF** [comment]
hello,
how did you setup the resources? I had the same issue at the beginning and resources were not properly setup

**Comment by fifou5555** [comment]
@ViRouF can you show us.

i have the same problem as the OP but with the button card. 
Clearly something is wrong in our installation

**Comment by WLammert** [comment]
@fifou5555  -> I found out that its not "easy readable" in the manual, but you need to install the decluttering-card and the button card via HACS->FRONTEND-> search and download from repo, than the error disappears. But still the examples SAKE1, SAKE1-M3, SAKE6, SAKE6-M3, are empty. Not sure whats wrong.

@ViRouF 
here the configuration.yaml
<img width="396" alt="image" src="https://user-images.githubusercontent.com/1142532/192239095-827c1464-97cd-4959-8548-90d1212085e8.png">

and the added resource:
![image](https://user-images.githubusercontent.com/1142532/192239453-cc184e2d-8780-4578-9eb2-625c1217a2f8.png)

**Comment by fifou5555** [comment]
@WLammert thanks i will try this. SAKE 1 and SAKE 2 are empty because you need an integration for weather. i dont really remember the name but sure you can find it in the SAKE 1 YAML
