### ISSUE TITLE
DevTools failed to load source map: Could not load content for https://REDACTED.com/local/community/swiss-army-knife-card/dist/svg-injector.map.js: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by johntdyer** [AmoebeLabs/swiss-army-knife-card#168]
## Bug report notice
I have reloaded the resources but I constantly getting this 404 since installing

So make sure your problem is not related to that!
- [X ] Yes, I'm sure that it is not a configuration mistake

## Bug description
Just installed the card, not even using yet, and I;m getting a 404 for some asset

I can see this file its looking for does not exist in the dir

```
➜  swiss-army-knife-card ls -al
total 244
drwxr-xr-x    2 root     root          4096 Sep 30 11:35 .
drwx------   86 root     root          4096 Sep 30 11:35 ..
-rw-r--r--    1 root     root         17722 Sep 30 11:35 SVGInjector.min.js
-rw-r--r--    1 root     root          5170 Sep 30 11:35 SVGInjector.min.js.gz
-rw-r--r--    1 root     root         16090 Sep 30 11:35 sak-css-definitions.yml
-rw-r--r--    1 root     root         20636 Sep 30 11:35 sak-svg-definitions.yml
-rw-r--r--    1 root     root           183 Sep 30 11:35 sak_templates.yaml
-rw-r--r--    1 root     root        137333 Sep 30 11:35 swiss-army-knife-card.js
-rw-r--r--    1 root     root         26808 Sep 30 11:35 swiss-army-knife-card.js.gz
```

but I can see that its being called from SVGInjector.min

```
➜  swiss-army-knife-card grep 'svg-injector.map.js' *
SVGInjector.min.js://# sourceMappingURL=./dist/svg-injector.map.js
➜  swiss-army-knife-card
```

### To Reproduce
refresh lovelace 

### Expected behavior
no 404
### Desktop browser (please complete the following information):
 - OS: OSX
 - Browser Chrome and Firefox
 - Version 103

**Additional context**

## (Optional): Suggested Solution
Any suggested solution to this bug.

**Comment by PeterGrace** [comment]
As mentioned in the comments of #161, I resolved this by downloading the svg-injector.map.js file from the svg-injector project and placing it in the required location.  I have a suspicion that @AmoebeLabs maybe neglected to add the file when prepping the rc3 release?  Not sure, but its a simple fix.  For reference, the file is is [over here](https://github.com/iconic/SVGInjector/tree/master/dist)

**Comment by peteralv** [comment]
are you using?

* https://github.com/flobacher/SVGInjector2
or
 * https://github.com/iconic/SVGInjector

**Comment by PeterGrace** [comment]
@peteralv I just tested both of them and both seem to work; I had originally been using iconic/SVGInjector but flobacher/SVGinjector2's file also seems to work interchangeably (unless I'm not reloading properly to see the difference.)

**Comment by peteralv** [comment]
Thanks 🙏 Peter

Skickat från min iPhone

14 okt. 2022 kl. 21:37 skrev Peter Grace ***@***.***>:

﻿

@peteralv<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpeteralv&data=05%7C01%7C%7Ce0e8d2e148d74c1eaa4408daae1b76a7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638013730216088871%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cJ5VY%2BryjL6i2h0GHIsrt4Q1oLH8xNbYtBm%2FmCBR%2BLE%3D&reserved=0> I just tested both of them and both seem to work; I had originally been using iconic/SVGInjector but flobacher/SVGinjector2's file also seems to work interchangeably (unless I'm not reloading properly to see the difference.)

**Comment by AmoebeLabs** [comment]
SAK is now using a different - maintained - SVG Injector which is included in the .js file itself

It has less bugs than the other 2 mentioned and/or things can be disabled to prevent some bugs from happening.

So closing this issue.
