### ISSUE TITLE
"Cannot read properties of undefined (reading 'state')"

### ISSUE THREAD

**Issue by PeterGrace** [AmoebeLabs/swiss-army-knife-card#169]
## Bug report notice

- [ ] Yes, I'm sure that it is not a configuration mistake  (Maybe?  How do I know what I don't know?)

## Bug description
As mentioned in #161, after fixing the templates issue I am now stuck with the below error message, "Cannot read properties of undefined (reading 'state').

The same behavior is shown in the Android home assistant application.

### To Reproduce
1. Attempt to load any VSAK view, regardless of template or not.
2. See error

### Expected behavior
Proper rendering of information from sensor states in the visualization

### Screenshots

![image](https://user-images.githubusercontent.com/967365/194678159-a4c90672-0157-4374-9e47-a574d5ae2e52.png)

### Desktop browser (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome
 - Version: 106.0.5249.91

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: Samsung Galaxy S21 Ultra
 - OS: Android

**Comment by Symbiot78** [comment]
@PeterGrace  - I had the same issue. Reason was that the entity did not exist.

**Comment by PeterGrace** [comment]
I can confirm that this error occurs if one or more sensors in your config don't exist.  In my case, I had a linkquality sensor configured which was disabled and as a result it caused the whole template to fail rendering.  Thanks @Symbiot78 !!!
