### ISSUE TITLE
Animated icons

### ISSUE THREAD

**Issue by alexandre72** [AmoebeLabs/swiss-army-knife-card#170]
Maybe it can be cool to have possibility to change icon, can be useful in animation state parts.

> animations:
>     \- state: \'15\'  
>     operator: \<=
>      styles:
>     icon:
>     name:battery-dead
>     - state: '25'  
>     operator: \<=
>      styles:
>     icon:
>     name:battery-warning

**Comment by mrgrlscz** [comment]
Oh yeah... i'm looking at a way to do this too!!

**Comment by AmoebeLabs** [comment]
Thanx for this idea!

This issue is of course a bit old. I will check this, as I thought this would already be possible.

If not, it will be on my to-do list, as it is a good idea!

**Comment by AmoebeLabs** [comment]
is inplemented: See #104 and #179
