### ISSUE TITLE
After upgrade to beta 2023.4.0b card is broken "r.setConfig is not a function"

### ISSUE THREAD

**Issue by rononline** [AmoebeLabs/swiss-army-knife-card#177]
[X] Yes, I'm sure that it is not a configuration mistake

Error "r.setConfig is not a function"

<img width="223" alt="Screenshot 2023-04-04 at 10 18 22" src="https://user-images.githubusercontent.com/10614484/229732059-e8251055-d1a9-4c4f-a776-fca0e5a6e087.png">

**Comment by rononline** [comment]
<img width="534" alt="Screenshot 2023-04-04 at 10 24 37" src="https://user-images.githubusercontent.com/10614484/229732923-1604960d-c49e-4de9-a467-4c26422988c8.png">

**Comment by MichelJourdain** [comment]
Same things for me.

![IMG_6563](https://user-images.githubusercontent.com/83040228/230213617-72caa275-0e7b-4669-bad0-6332ad05d6e8.jpeg)

**Comment by lougovsk** [comment]
Have the same issue here. Looks like it is related to this issue in custom card helper. There was a breaking change in home assistant 04.2023 .
https://github.com/custom-cards/custom-card-helpers/issues/72

This probably causes null object for getLovelace call.

**Comment by RHG2208** [comment]
Same problem here!

![Schermafbeelding 2023-04-07 150341](https://user-images.githubusercontent.com/103814940/230613682-def1ae6e-bec8-4e48-84ce-77515a5746b3.png)

**Comment by AmoebeLabs** [comment]
This commit: https://github.com/AmoebeLabs/swiss-army-knife-card/commit/22197063f84e836468e13051d68595d1fdfbaff4 should have fixed this problem and is part of release https://github.com/AmoebeLabs/swiss-army-knife-card/releases/tag/v1.0.0-rc.4
