### ISSUE TITLE
6 digits number and comma/dot seperator

### ISSUE THREAD

**Issue by cryptooth** [AmoebeLabs/swiss-army-knife-card#216]
I have 6 digits of sensor data. I can see it on HA's standard cards with no problem. For example, I see the data in 123456 format from SQL as 123.456 in the HA panel.

But when I create a card with SAKS, this data shows as 123456. What needs to be done to ensure a more comfortable reading? Comma or dots?

any advice?

**Comment by AmoebeLabs** [comment]
This looks as if the Number format is not correctly applied by SAK. That is a bug.
Number format is set in the personal config part of HA.

NTS:
- buildState() does not interpret Number format as it should

**Comment by AmoebeLabs** [comment]
This issue will get solved by #227

**Comment by AmoebeLabs** [comment]
Closed due to #227
